### ISSUE TITLE
Logger.log became a macro in 1.1

### ISSUE THREAD

**Issue by ghost** [mprymek/fulight#1]
The code located at [lager.erl](https://github.com/mprymek/fulight/blob/master/src/lager.erl) is bound to fail, because Logger.log became a [macro](https://github.com/elixir-lang/elixir/blob/v1.1.0/lib/logger/lib/logger.ex#L515-L517) with Elixir 1.1.

In my opinion (and according to [the documentation](http://elixir-lang.org/docs/stable/logger/Logger.html#log/3)) your code should call Logger.warn/debug/info instead of log/3.

A stacktrace can be seen [here](http://elixir-lang.org/docs/stable/logger/Logger.html#log/3). Have a nice day!

**Comment by mprymek** [comment]
P.S. @Annwenn I'm very sory for late response, GitHub did not inform me about this issue :(

**Comment by ghost** [comment]
no worries ;)
